preprocess:
  input_data:
    s3_uri_postfix: abalone/abalone-dataset.csv
    content_type: text/csv
  batch_data:
    s3_uri_postfix: abalone/abalone-dataset-batch.csv
    content_type: text/csv
  instance:
    count: 1 
    script: preprocess.py
train:
  model:
    s3_uri_postfix: AbaloneTrain
    type: xgboost
    version: 1.0-1
    hyper_params:
      objective: "reg:linear"
      num_round: 50
      max_depth: 5
      eta: 0.2
      gamma: 4
      min_child_weight: 6
      subsample: 0.7
      silent: 0
  instance:
    type: "ml.m5.xlarge"
    count: 1
evaluate:
  instance:
    type: "ml.m5.xlarge"
    count: 1
    script: evaluate.py
register_model:
  group_name: AbaloneModelPackageGroupName